version: "3"

services:
  database:
    environment:
      - POSTGRES_DB=tempostgres_db
      - POSTGRES_PASSWORD=tem.pass
      - POSTGRES_USER=doc
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  hub:
    image: selenium/hub:3.14
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    volumes:
      - /dev/shm:/dev/shm

  firefox:
    image: selenium/node-firefox:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    volumes:
      - /dev/shm:/dev/shm

volumes:
  postgres_data: